const products = [
  {
    id: 1,
    title: "Cordless Drill Professional Combo Drill And Screwdriver",
    price: 200,
    oldPrice: 300,
    rating: "1k+ Ratings",
    tag: "10% Off",
    tagType: "offer",
    image: "/src/assets/Images/shop-1.webp",
  },
  {
    id: 2,
    title: "Professional Cordless Drill Power Tools Set Competitive",
    price: 100,
    oldPrice: 120,
    rating: "3k+ Ratings",
    tag: "New",
    tagType: "new",
    image: "/src/assets/Images/shop-2.webp",
  },
  {
    id: 3,
    title: "DFMLab 20V Max XX Oscillating Multi Tool Variable",
    price: 300,
    oldPrice: 400,
    rating: "2k+ Ratings",
    tag: "Sale",
    tagType: "sale",
    image: "/src/assets/Images/shop-3.webp",
  },
  {
    id: 4,
    title: "Power Tools Set Chienese Drill Manufacturer Product",
    price: 400,
    oldPrice: 500,
    rating: "7k+ Ratings",
    tag: "New",
    tagType: "new",
    image: "/src/assets/Images/shop-4.webp",
  },
  {
    id: 5,
    title: "High Quality Electric Hand Planner 4/3 Inch Drill",
    price: 100,
    oldPrice: 120,
    rating: "5k+ Ratings",
    tag: "15% off",
    tagType: "new",
    image: "/src/assets/Images/shop-12.webp",
  },
   {
    id: 6,
    title: " Professional Combo Drill And ScrCordless Drillewdriver",
    price: 200,
    oldPrice: 300,
    rating: "1k+ Ratings",
    tag: "10% Off",
    tagType: "offer",
    image: "/src/assets/Images/shop-14.webp",
  },
  {
    id: 7,
    title: "Professional Cordless Drill Power Tools Set Competitive",
    price: 100,
    oldPrice: 120,
    rating: "3k+ Ratings",
    tag: "New",
    tagType: "new",
    image: "/src/assets/Images/shop-15.webp",
  },
  {
    id: 8,
    title: "DFMLab 20V Max XX Oscillating Multi Tool Variable",
    price: 300,
    oldPrice: 400,
    rating: "2k+ Ratings",
    tag: "Sale",
    tagType: "sale",
    image: "/src/assets/Images/shop-16.webp",
  },
  {
    id: 9,
    title: "Power Tools Set Chienese Drill Manufacturer Product",
    price: 400,
    oldPrice: 500,
    rating: "7k+ Ratings",
    tag: "New",
    tagType: "new",
    image: "/src/assets/Images/shop-17.webp",
  },
  {
    id: 10,
    title: "High Quality Electric Hand Planner 4/3 Inch Drill",
    price: 100,
    oldPrice: 120,
    rating: "5k+ Ratings",
    tag: "15% off",
    tagType: "new",
    image: "/src/assets/Images/shop-13.webp",
  },
    {
    id: 11,
    title: "Cordless Drill Professional Combo Drill And Screwdriver",
    price: 200,
    oldPrice: 300,
    rating: "1k+ Ratings",
    tag: "10% Off",
    tagType: "offer",
    image: "/src/assets/Images/shop-5.webp",
  },
  {
    id: 12,
    title: "Professional Cordless Drill Power Tools Set Competitive",
    price: 100,
    oldPrice: 120,
    rating: "3k+ Ratings",
    tag: "New",
    tagType: "new",
    image: "/src/assets/Images/shop-6.webp",
  },
  {
    id: 13,
    title: "DFMLab 20V Max XX Oscillating Multi Tool Variable",
    price: 300,
    oldPrice: 400,
    rating: "2k+ Ratings",
    tag: "Sale",
    tagType: "sale",
    image: "/src/assets/Images/shop-7.webp",
  },
  {
    id: 14,
    title: "Power Tools Set Chienese Drill Manufacturer Product",
    price: 400,
    oldPrice: 500,
    rating: "7k+ Ratings",
    tag: "New",
    tagType: "new",
    image: "src/assets/Images/shop-4.webp",
  },
];

export default products;
